# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 5050
  productcatalogserviceaddr: "productcatalogservice:3550"
  shippingserviceaddr: "shippingservice:50051"
  paymentserviceaddr: "paymentservice:50051"
  emailserviceaddr: "emailservice:5000"
  currencyserviceaddr: "currencyservice:7000"
  cartserviceaddr: "cartservice:7070"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

  #  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaegerConfigName: jaeger-config
jaegerSecretName: jaeger-access

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo:
  - inventory-management-svc-solution

runtime: nodejs

serviceMesh:
  sidecar: true
